# netlify.toml
[build]
  base = "Frontend"
  publish = "dist"
  command = "npm run build"

# Proxy: todo lo que empiece por /api va al backend en Vercel
[[redirects]]
  from = "/api/*"
  to = "https://sistema-de-cotizacion-y-gastos.vercel.app/api:splat"
  status = 200
  force = true
