[build]
  base = "Frontend"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://sistema-de-cotizacion-y-gastos.vercel.app/api/:splat"
  status = 200
  force = true
